query ($idpost: ID!) {  
  post(id: $idpost) {
    id,
    titulo,
    subtitulo,
    resumen,
    contenido,
    imagen{
      id, name, alternativeText, caption, url
    },
    creador,
    fechapublicacion,
    publicado,
    seccion,
    etiquetas,
  }
}
