query ($limit: Int=1){
  listaPost: posts(
      sort: "fechapublicacion:DESC",
      limit:$limit,
      where: {publicado:true, destacado:true}
    ){
    id,
    titulo,
    subtitulo,
    resumen,
    contenido,
    imagen{
      id, name, alternativeText, url
    },
    creador,
    fechapublicacion,
    publicado,
    seccion,
    etiquetas,
    
  }
}

